### ISSUE TITLE
script to push the image from MMC to eMMC

### ISSUE THREAD

**Issue by bunny9971** [OLIMEX/olimage#1]
proposing this as a new feature enhancement to include the script to push the image from `MMC` to  `eMMC`  
`nand-sata-install` script missing.

**Comment by stefansaraev** [comment]
https://github.com/OLIMEX/olinuxino-tools/blob/master/src/scripts/olinuxino-sd-to-emmc
https://github.com/OLIMEX/olinuxino-tools/blob/master/src/scripts/olinuxino-sd-to-sata
