### ISSUE TITLE
linux-headers are missing KConfig

### ISSUE THREAD

**Issue by gamelaster** [OLIMEX/olimage#2]
Hello,
I'm trying to build out-of-tree module, sadly, I have this error:
```bash
make -s -C /lib/modules/5.10.14-olimex/build SUBDIRS=/app/i_driver_native modules
can't find file Kconfig
make[3]: *** [scripts/kconfig/Makefile:71: syncconfig] Error 1
make[2]: *** [Makefile:602: syncconfig] Error 2
make[1]: *** [Makefile:710: include/config/auto.conf.cmd] Error 2
make: *** [Makefile:60: default] Error 2
```

I seen there was some changes in 5.2+, although, I have tested this module with 5.0 and everything works well.

(Temporary solved by building it towards olinuxino kernel source code)

**Comment by stefansaraev** [comment]
you need to also install linux-headers-5.10.14-olimex

**Comment by gamelaster** [comment]
Hi @stefansaraev I had some issues with cross-compiling it from kernel source, I can somewhere find updated debpkg?
