### ISSUE TITLE
How to build a patched kernel?

### ISSUE THREAD

**Issue by jech** [OLIMEX/olimage#5]
The A64 boards I own used to be a great platform for testing kernel patches.  With the new build system, it is no longer obvious how to build a patched kernel.

Please document how to build a patched kernel with olimage.  Thanks.

**Comment by DanKoloff** [comment]
There are now instructions towards the end of this document:

https://github.com/OLIMEX/OLINUXINO/blob/master/DOCUMENTS/OLIMAGE/Olimage-guide.pdf
